# Generated by Django 5.0.7 on 2024-08-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile_img',
            new_name='img',
        ),
    ]
