# Generated by Django 5.0.7 on 2024-08-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='profile_img',
        ),
    ]
