# Generated by Django 5.0.7 on 2024-08-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_feed_profile_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photos.feed'),
        ),
    ]
